-- Tabla para almacenar señales económicas (histórico de datos)
CREATE TABLE IF NOT EXISTS economic_signals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  indicator_id TEXT NOT NULL,
  date TEXT NOT NULL,
  value NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(indicator_id, date)
);

-- Tabla para almacenar alertas detectadas (el "cerebro")
CREATE TABLE IF NOT EXISTS economic_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  indicator_id TEXT NOT NULL,
  indicator_name TEXT,              -- Nombre amigable para humanos
  alert_type TEXT NOT NULL,
  date TEXT NOT NULL,
  description TEXT,
  severity TEXT DEFAULT 'medium',   -- high, medium, low
  value_change NUMERIC,             -- Magnitud del cambio
  ai_strategy TEXT,                 -- Estrategia accionable de Gemini
  regional_context TEXT,            -- Contexto específico (ej: MTY/NL)
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(indicator_id, alert_type, date)
);

-- Tabla para configuración dinámica (API Keys, timeouts, etc.)
CREATE TABLE IF NOT EXISTS app_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_key TEXT UNIQUE NOT NULL,
  config_value TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insertar llave de Gemini inicial (opcional, como respaldo)
-- INSERT INTO app_config (config_key, config_value) VALUES ('GEMINI_API_KEY', 'TU_LLAVE_AQUI') ON CONFLICT DO NOTHING;

-- Habilitar RLS
ALTER TABLE economic_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE economic_alerts ENABLE ROW LEVEL SECURITY;

-- Políticas de lectura pública (Idempotentes)
DROP POLICY IF EXISTS "Public Read Access Signals" ON economic_signals;
CREATE POLICY "Public Read Access Signals" ON economic_signals FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Access Alerts" ON economic_alerts;
CREATE POLICY "Public Read Access Alerts" ON economic_alerts FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Access Config" ON app_config;
CREATE POLICY "Public Read Access Config" ON app_config FOR SELECT USING (true);
