-- Tabla para almacenar señales económicas (histórico de datos)
CREATE TABLE IF NOT EXISTS economic_signals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  indicator_id TEXT NOT NULL,
  date TEXT NOT NULL,
  value NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(indicator_id, date)
);

-- Tabla para almacenar alertas detectadas (el "cerebro")
CREATE TABLE IF NOT EXISTS economic_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  indicator_id TEXT NOT NULL,
  alert_type TEXT NOT NULL,
  date TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(indicator_id, alert_type, date)
);

-- Habilitar RLS
ALTER TABLE economic_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE economic_alerts ENABLE ROW LEVEL SECURITY;

-- Política de lectura pública
CREATE POLICY "Public Read Access Signals" ON economic_signals FOR SELECT USING (true);
CREATE POLICY "Public Read Access Alerts" ON economic_alerts FOR SELECT USING (true);
